# Generated by Django 5.0.2 on 2024-03-19 16:32

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_api', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bio', models.TextField(blank=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Phone Number')),
                ('education', models.ManyToManyField(to='core_api.education')),
                ('experience', models.ManyToManyField(to='core_api.experience')),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core_api.location')),
                ('skills', models.ManyToManyField(to='core_api.skill')),
            ],
        ),
    ]
